services:
  - type: web
    name: linkedin-carousel-generator
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && playwright install chromium"
    startCommand: "streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true"
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
    autoDeploy: true
    healthCheckPath: / 